version: '3'

services:
  hy-environment:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    restart: unless-stopped

  org-emacs:
    build:
      context: .
      dockerfile: Dockerfile
    command: emacs -Q --daemon
    volumes:
      - .:/app
      - ./init.el:/root/.emacs.d/init.el
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    
  make-runner:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "while true; do sleep 1; done"  # Keep container running
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
